language: csharp
mono: none
dotnet: 3.1

before_script:
  - dotnet restore

script:
  - dotnet test test/trybot.tests.csproj -c Release -f netcoreapp3.1

jobs:
  fast_finish: true
  include:
    - os: linux
      dist: xenial

    - os: osx
      dotnet: 3.1.102
      osx_image: xcode11.3 