deploy:
- provider: NuGet
  api_key:
    secure: tb8mXs1vxgjA5zmrx5JZqpxqHpDQltFTJ1ldpHNb+JPI0WytKILZ/IkegZATe4Aq

- provider: NuGet
  server: https://nuget.pkg.github.com/z4kn4fein/index.json
  artifact: /.nupkg/
  skip_symbols: true
  username: z4kn4fein
  api_key:
    secure: TaIug8cHioxT2qDznFpGtDinZiDi+20pEMQZUVAATWCvGLG9Y5LrjaxDUQtGyt38

- provider: GitHub
  tag: $(build_version)
  release: Trybot v$(build_version)
  auth_token:
    secure: TaIug8cHioxT2qDznFpGtDinZiDi+20pEMQZUVAATWCvGLG9Y5LrjaxDUQtGyt38
  artifact: /.*\.nupkg|.*\.snupkg/

environment:
  build_version: ''

image: Visual Studio 2019
  
configuration: Release

install:
- ps: |
    $env:build_version = Get-Content ".version"
    Update-AppveyorBuild -Version "$env:build_version-$env:appveyor_build_number"
    dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 "src\trybot.csproj" $env:build_version $env:build_version

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% trybot.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% /p:ContinuousIntegrationBuild=true trybot.sln

after_build:
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\artifacts src\trybot.csproj

artifacts:
- path: artifacts\Trybot.*.nupkg
  name: NuGet
- path: artifacts\Trybot.*.snupkg
  name: NuGet Symbol Packages

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true