deploy:
- provider: NuGet
  api_key:
    secure: doqtwSE1NadH7pf4jqYifDu4tcXzsNiJtPWOccnbUrhSnIJX+5js7m8z+kV9LNJ2

- provider: GitHub
  tag: $(build_version)
  release: Trybot v$(build_version)
  auth_token:
    secure: TaIug8cHioxT2qDznFpGtDinZiDi+20pEMQZUVAATWCvGLG9Y5LrjaxDUQtGyt38
  artifact: /.*\.nupkg/

environment:
  build_version: ''

image: Visual Studio 2017
  
configuration: Release

install:
- ps: |
    $env:build_version = Get-Content ".version"
    Update-AppveyorBuild -Version "$env:build_version-$env:appveyor_build_number"
    dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 "src\trybot.csproj" $env:build_version $env:build_version

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% trybot.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% trybot.sln

after_build:
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\artifacts src\trybot.csproj

artifacts:
- path: artifacts\Trybot.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true