deploy:
- provider: NuGet
  server: https://www.myget.org/F/pcsajtai/api/v2/package
  symbol_server: https://www.myget.org/F/pcsajtai/symbols/api/v2/package
  api_key:
    secure: 2bITagXOj2s3bTJaGXh8/iyWtST8OQOFaMM+0GAKgZts9OjCVCiV7C+E/0SYsM6M

environment:
  build_version: ''

skip_tags: true

image: Visual Studio 2017
  
configuration: Release

install:
- ps: |
    $env:build_version = Get-Content ".version"
    Update-AppveyorBuild -Version "$env:build_version-preview-$env:appveyor_build_number"
    dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 "src\trybot.csproj" $env:build_version $env:appveyor_build_version

build_script:
- msbuild /t:Restore /p:Configuration=%configuration% trybot.sln
- msbuild /t:Build /p:Configuration=%configuration% trybot.sln

after_build:
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%configuration% /p:PackageOutputPath=..\artifacts src\trybot.csproj

test_script:
- dotnet test test\trybot.tests.csproj  -f net45 -c %configuration% --no-build
- dotnet test test\trybot.tests.csproj  -f netcoreapp1.0 -c %configuration% --no-build
- dotnet test test\trybot.tests.csproj  -f netcoreapp2.0 -c %configuration% --no-build

after_test:
- ps: . .\set-debug-type.ps1 "src\trybot.csproj"
- ps: . .\coverage.ps1

artifacts:
- path: artifacts\Trybot.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true